### ISSUE TITLE
Not compatible with Spring Boot 2

### ISSUE THREAD

**Issue by omau** [zalando-incubator/put-it-to-rest#72]
On upgrade to new version of Spring Boot (1.5 won't support Java 9),
I see the following problem:

```
java.lang.NoClassDefFoundError: org/springframework/boot/bind/PropertiesConfigurationFactory
	at org.zalando.putittorest.RestClientPostProcessor.getSettings(RestClientPostProcessor.java:93) ~[put-it-to-rest-0.13.0.jar:na]
	at org.zalando.putittorest.RestClientPostProcessor.postProcessBeanDefinitionRegistry(RestClientPostProcessor.java:75) ~[put-it-to-rest-0.13.0.jar:na]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:119) ~[spring-context-5.0.0.RELEASE.jar:5.0.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:693) ~[spring-context-5.0.0.RELEASE.jar:5.0.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531) ~[spring-context-5.0.0.RELEASE.jar:5.0.0.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:122) ~[spring-boot-2.0.0.M5.jar:2.0.0.M5]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) [spring-boot-2.0.0.M5.jar:2.0.0.M5]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:386) [spring-boot-2.0.0.M5.jar:2.0.0.M5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.0.M5.jar:2.0.0.M5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1245) [spring-boot-2.0.0.M5.jar:2.0.0.M5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1233) [spring-boot-2.0.0.M5.jar:2.0.0.M5]
```

**Comment by whiskeysierra** [comment]
I'm going to deprecate this project in favor of https://github.com/zalando/riptide/tree/master/riptide-spring-boot-starter. Can you re-create this issue there?
